CREATE TABLE IF NOT EXISTS user
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    VARCHAR(10) NOT NULL,
    name     VARCHAR(20),
    email    VARCHAR(20) NOT NULL,
    birthday DATE
    );

CREATE TABLE IF NOT EXISTS friendship_status
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(10) NOT NULL
    );

CREATE TABLE IF NOT EXISTS friend
(
    user_id              INTEGER REFERENCES user (user_id) ON DELETE CASCADE,
    friend_id            INTEGER,
    friendship_status_id INTEGER REFERENCES friendship_status (id) ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS film
(
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(30)  NOT NULL,
    description  VARCHAR(200) NOT NULL,
    release_date DATE         NOT NULL,
    duration     LONG         NOT NULL,
    rate         INTEGER
    );

CREATE TABLE IF NOT EXISTS liked_film
(
    user_id INTEGER REFERENCES user (user_id) ON DELETE RESTRICT,
    film_id INTEGER REFERENCES film (film_id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS genre
(
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(20) NOT NULL
    );

CREATE TABLE IF NOT EXISTS genre_film
(
    genre_id INTEGER REFERENCES genre (genre_id) ON DELETE RESTRICT,
    film_id  INTEGER REFERENCES film (film_id) ON DELETE CASCADE
    );